### ISSUE TITLE
Submit issues to plotnine

### ISSUE THREAD

**Issue by has2k1** [tdhopper/pythonplot.com#1]
This is a very helpful project, I have linked to it in the [plotnine documentation](http://plotnine.readthedocs.io/en/stable/external-resources.html). The bugs have also been fixed and a new release is out.

For the "unsmoothed line", you are missing an optional package [scikit-misc](http://github.com/has2k1/scikit-misc) which implements [loess](https://has2k1.github.io/scikit-misc/loess.html) smoothing. Warning though, it may be hard to install if you are on windows, sorry for that.

Also, if you are going to dive deeper into what you can do with `ggplot2` and happen to run into use-cases of the [scales](https://github.com/hadley/scales) package (e.g transformations), you should find similar functionality in [mizani](https://mizani.readthedocs.io/en/stable/). It is a installed as a dependency.

 Please remember to [report](https://github.com/has2k1/plotnine/issues) any other issues you encounter.

**Comment by tdhopper** [comment]
@has2k1: Thanks for the feedback. I installed scikit-miss, but the lowess line is [still a bit odd](http://pythonplot.com/#stacked-smooth-line-and-scatter).
