### ISSUE TITLE
Clarify contributing guidelines/goals

### ISSUE THREAD

**Issue by jwhendy** [tdhopper/pythonplot.com#10]
Could you layout your ultimate hopes for this project? Like, do you just want to show the default, out of the box plot type with each library? Or do you want to use some library as a reference and show how to recreate it with the other libraries?

As a really simple example of where this would help. It looks like `pandas` used to output this (screenshot of your current site):

![2017-12-26_125019](https://user-images.githubusercontent.com/379357/34362703-7e63ec68-ea3b-11e7-8968-1ea546be9c77.png)

When I reproduce this code now, I get:

![2017-12-26_125005](https://user-images.githubusercontent.com/379357/34362707-855bf89e-ea3b-11e7-82bc-7cb161bb320e.png)

I am in the process of adding `seaborn` examples to this and it's default is multi-colored as well. Intuitively, I wanted to make it replicate how all the others looked so I did:
```
fig = sns.countplot(y='manufacturer',
                    color='blue',
                    data=mpg)
fig.set_title('Number of Cars by Make')
```

Then I second-guessed myself and thought you might prefer the most raw/as-is representation of each library. Let me know your preference/overall spirit and I'll attempt to match it with any contributions.

**Comment by tdhopper** [comment]
@jwhendy I'm more inclined towards less configuration on the plots (and thus taking them as-is). My own use for this site is to remember basic syntax for a variety of common plots, not more complex styling and config. I'd like to add examples at some point showing more about how to configure plots, but I don't the bandwidth at the moment.
