### ISSUE TITLE
Preference on plotly syntax

### ISSUE THREAD

**Issue by jwhendy** [tdhopper/pythonplot.com#11]
Could you confirm the preference to use 'raw' syntax in rendering json via `plotly`?

```
fig = {
    'data' : [{
        'type' : 'bar',
        'x' : mpgGrouped.values.tolist(),
        'y' : mpgGrouped.index.tolist(),
        'orientation' : 'h'
        
    }],
    'layout' : {
        'title' : 'Number of Cars by Make'
    }
}
```

In my looking into `plotly`, I haven't seen this much (at all?). I think [their docs](https://plot.ly/python/bar-charts/) indicate doing the above like so:
```
data = [go.Bar(x=mpgGrouped.values.tolist(),
               y=mpgGrouped.index.tolist(),
               orientation='h')]
layout = go.Layout({'title': 'Number of Cars by Make'})
fig = go.Figure(data=data, layout=layout)
```

Honestly, there's not much difference, and in some ways your current version is more concise/clear. I *do* wonder if the `go.Foo` syntax is going to be more widespread/understood by users vs. creating the json dict directly.

**Comment by tdhopper** [comment]
I've never used plotly. Someone else contributed these examples. I'd be happy to have a PR that uses the other style.
