### ISSUE TITLE
non-png output

### ISSUE THREAD

**Issue by tobyhodges** [tdhopper/pythonplot.com#4]
This is a really nice idea, and a good start. After reading the note about Bokeh in the Readme, my immediate thought was that I could contribute some examples using `bokeh.charts` or `bokeh.plotting`.

Unfortunately, this is limited by the requirement for plots to be output as `png` from the code cells in the notebook. Bokeh output is typically HTML, which can be rendered inline in a Jupyter notebook with `bokeh.io.output_notebook()` ([docs](http://bokeh.pydata.org/en/latest/docs/reference/io.html)). With the latest release, it became possible to output as `png` and `svg` but these options either require additional dependencies, or are incompatible with output into a notebook. For more, see [here](http://bokeh.pydata.org/en/latest/docs/user_guide/export.html) and [here](http://bokeh.pydata.org/en/latest/docs/reference/io.html).

If you are happy to accept examples that either don't output `png` into the notebook, or that do output `png` but not inline and with additional dependencies on `selenium`, I would like to contribute.

**Comment by tdhopper** [comment]
The most important thing to me right now is that the plots are rendered in a way that I can display responsively using Bootstrap. PNG is nice because I can just use the [img-fluid](https://v4-alpha.getbootstrap.com/content/images/#responsive-images) class. That should work with SVGs too.

**Comment by tdhopper** [comment]
@tobyhodges: I [created a way](https://github.com/tdhopper/pythonplot.com/commit/2b4e80e46d8c453b833b4cf98fc86e9c0fa9e21d) to display Bokeh plots: http://pythonplot.com/index.html#simple-histogram

The notebook is just running `Image(export_png(p))` to render the bokeh png (via selenium) to the output cell.

**Comment by tdhopper** [comment]
For some reason, I'm able to render these locally (on my Mac), but it's failing on travis https://travis-ci.org/tdhopper/pythonplot.com/builds/247215019

**Comment by tdhopper** [comment]
Given [this](https://github.com/bokeh/bkcharts/issues/75#issuecomment-311161801), I think I'm going to give up on using Bokeh charts for the time being.

**Comment by tobyhodges** [comment]
Ok, thanks for investigating. I'll keep an eye on the issue discussion in the `bokeh` project and submit a simple `bokeh` example once the problem has been fixed.
